### ISSUE TITLE
how do you deal with the variant length of audio 

### ISSUE THREAD

**Issue by CZFuChason** [RayanWang/Speech_emotion_recognition_BLSTM#14]
Hi RayanWang,

I have gone through your code these days, thank you so much for your sharing and it is really nice work.

But I still have a question, can you tell me in which part of your code is to deal with the length of the audio data. I also work on Berlin Dataset, but the audio has a different length from each other. I used the padding method but the results were not that good as yours.

I am looking forward to getting your reply.

Chason

**Comment by RayanWang** [comment]
Hi CZFuChason,

I am using sequence.pad_sequences to fill the data with a special value to keep all data length consistent. And then in creating the network, use Masking method to ignore this value during training.
