### ISSUE TITLE
Real Time Application

### ISSUE THREAD

**Issue by harryxu-yscz** [RayanWang/Speech_emotion_recognition_BLSTM#2]
Thanks for sharing this awesome repo! I wonder if the current model would handle real time prediction on videos? Could you briefly outline how to do that?

Thanks in advance!

**Comment by RayanWang** [comment]
Hello harryxu-yscz,
I have never test this method in videos. The "Real Time" in my imagination is to make prediction after collecting data for a period of time (ex: after getting a complete speech sentence). You may have to do feature engineering before training and    fine-tune the hyper-parameters such as # of nodes in hidden layers by means of hyperas. This is the part that I currently think of that may have to pay attention.

Good luck!

**Comment by thaingiW** [comment]
What code should be modified in audioFeatureExtraction.py?.What code should be added in stFeatureSpeed.?

**Comment by thaingiW** [comment]
I want to run speech-emotion-recognition-BLSTM.

**Comment by RayanWang** [comment]
About audioFeatureExtraction.py, please cast the index variable to int format, just follow the raised exception and modify them. No technical issues need to be modified.

**Comment by thaingiW** [comment]
Thank you very much!!

**Comment by hirunifernando** [comment]
=========================================================
Writing berlin data set to file...
Traceback (most recent call last):
  File "/home/lwin/speech-emotion/Speech_emotion_recognition_BLSTM-master/find_best_model.py", line 163, in <module>
    functions.feature_extract(ds.data, nb_samples=len(ds.targets), dataset=dataset)
  File "/home/lwin/speech-emotion/Speech_emotion_recognition_BLSTM-master/utility/functions.py", line 20, in feature_extract
    hr_pitch = audioFeatureExtraction.stFeatureSpeed(x, Fs, globalvars.frame_size * Fs, globalvars.step * Fs)
  File "/usr/local/lib/python3.5/dist-packages/pyAudioAnalysis/audioFeatureExtraction.py", line 669, in stFeatureSpeed
    [fbank, freqs] = mfccInitFilterBanks(Fs, nfft, lowfreq, linsc, logsc, nlinfil, nlogfil)
TypeError: mfccInitFilterBanks() takes 2 positional arguments but 7 were given

=================================================================
How to solve this issue.plz help me .Thank u
