### ISSUE TITLE
meet a issue in python3

### ISSUE THREAD

**Issue by Haorotu** [RayanWang/Speech_emotion_recognition_BLSTM#7]
![image](https://user-images.githubusercontent.com/28502249/45809500-e71bba00-bcfa-11e8-98da-f58175a29aec.png)

  File "F:/123/find_best_model.py", line 160, in <module>
    ds = pickle.load(open(dataset + '_db.p', 'rb'))

FileNotFoundError: [Errno 2] No such file or directory: 'berlin_db.p'

**Comment by RayanWang** [comment]
OK, first you have to run the code with "-l" as argument at your first run to generate the db file. Then you don't need this argument again.

**Comment by Haorotu** [comment]
Due to using python3,I ask for your help how to write the code in this issue."python find_best_model.py -d "berlin" -p [berlin data path] -l -e -c 7" how to transform. Thank you.

**Comment by RayanWang** [comment]
Please enter the following in terminal: 
python "F:/123/find_best_model.py" -d "berlin" -p  [berlin data path] -l -e -c 7
which [berlin data path] is the training data directory such as "F:/Berlin/download/wav/"

**Comment by Haorotu** [comment]
Thanks for your help to solove my problems,I also meet another issue.Please help me in your spare time.Thanks very much.

F:\123>python find_best_model.py -d "berlin" -p "F:/123/wav/" -l -e -c 7
Using TensorFlow backend.
Writing berlin data set to file...
F:\Anaconda3\lib\site-packages\pyAudioAnalysis\audioFeatureExtraction.py:66: RuntimeWarning: invalid value encountered in true_divide
  Xt = Xt / Xt.max()
Traceback (most recent call last):
  File "find_best_model.py", line 163, in <module>
    functions.feature_extract(ds.data, nb_samples=len(ds.targets), dataset=dataset)
  File "F:\123\utility\functions.py", line 17, in feature_extract
    f = audioFeatureExtraction.stFeatureExtraction(x, Fs, globalvars.frame_size * Fs, globalvars.step * Fs)
  File "F:\Anaconda3\lib\site-packages\pyAudioAnalysis\audioFeatureExtraction.py", line 579, in stFeatureExtraction
    chromaNames, chromaF = stChromaFeatures(X, Fs, nChroma, nFreqsPerChroma)
  File "F:\Anaconda3\lib\site-packages\pyAudioAnalysis\audioFeatureExtraction.py", line 277, in stChromaFeatures
    C2[0:C.shape[0]] = C
ValueError: could not broadcast input array from shape (200) into shape (192)

F:\123>

**Comment by RayanWang** [comment]
Please upgrade the project to the newest version.

**Comment by Haorotu** [comment]
Excuse me,I'm so sorry to disturb again.I meet a issue at the processing of using the newest version.Please help me !Thanks very much!
![image](https://user-images.githubusercontent.com/28502249/45871069-0d0a9280-bdbf-11e8-8859-08ab3806a791.png)

**Comment by RayanWang** [comment]
Only reserve the first two arguments and it will work.

**Comment by Haorotu** [comment]
I feel confused about how to revise this error in the code.Please help.Thank you

**Comment by RayanWang** [comment]
Modify codes: mfccInitFilterBanks(fs, nfft, ...) -> mfccInitFilterBanks(fs, nfft), just leave fs and nfft.

**Comment by Haorotu** [comment]
This issue is already solved by myself,Thanks very much.Happy mid-Autumn Festival

**Comment by Haorotu** [comment]
Dear Rayan
![image](https://user-images.githubusercontent.com/28502249/45936148-d4003700-bfe5-11e8-9735-2305b21e2e7b.png)

I’m so sorry to disturb you again.Please help me.I hope to study your code careful and serious.I sincerely thank you for sharing this code.I feel worry about this issue.I don't know how to revise the code.Please help me .Thanks very much.

**Comment by RayanWang** [comment]
Cast the type of variable 'nfft' to integer in method stFeatureSpeed, and it will work.

**Comment by Haorotu** [comment]
Thanks,but I knew "nfft" should be a 'int',I don't know how to revise it.I'm sorry to disturb you again.Please help.Thank you very much

**Comment by RayanWang** [comment]
Comment out the invocation of method 'mfccInitFilterBanks' in stFeatureSpeed, and modify nfft like this: 'nfft = int(win / 2)'
