### ISSUE TITLE
which method does this repo based on?

### ISSUE THREAD

**Issue by ChuanjunLAN** [RayanWang/Speech_emotion_recognition_BLSTM#9]
Hi RayanWANG, i have go through ur repo, first of all, that's a good work, thx for ur share.
But, i want to know the method u use. I see that u have put 2 reference here, but which one do u based on?
I want more information to understand better the algorithm.
If u can tell the one u use, that will be great.
Thx.

**Comment by RayanWang** [comment]
hI ChuanjunLAN, this repo is based on "Automatic speech emotion recognition using recurrent neural networks with local attention" and the same with video from Microsoft.
